from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from db import get_db, Machine, Report, Metric, AuditLog, Alert
from auth import get_current_user, require_operator, User
from datetime import datetime
import os, textwrap

router = APIRouter(prefix="/reports", tags=["reports"])
REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

def _generate_pdf(machine: Machine, metrics: list, logs: list,
                  alerts: list) -> str:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                    Table, TableStyle, HRFlowable)
    from reportlab.lib.units import cm

    fname    = f"jenix_report_{machine.hostname}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    fpath    = os.path.join(REPORTS_DIR, fname)
    doc      = SimpleDocTemplate(fpath, pagesize=A4,
                                 leftMargin=2*cm, rightMargin=2*cm,
                                 topMargin=2*cm,  bottomMargin=2*cm)
    styles   = getSampleStyleSheet()
    story    = []

    # Styles
    title_style = ParagraphStyle("title", fontSize=24, textColor=colors.HexColor("#00bcd4"),
                                  spaceAfter=6, fontName="Helvetica-Bold")
    h2_style    = ParagraphStyle("h2", fontSize=14, textColor=colors.HexColor("#00bcd4"),
                                  spaceBefore=12, spaceAfter=6, fontName="Helvetica-Bold")
    body_style  = styles["BodyText"]
    warn_style  = ParagraphStyle("warn", fontSize=10, textColor=colors.HexColor("#ff9800"),
                                  fontName="Helvetica-Bold")
    crit_style  = ParagraphStyle("crit", fontSize=10, textColor=colors.HexColor("#f44336"),
                                  fontName="Helvetica-Bold")

    # ── Cover ──────────────────────────────────────────────────────────────
    story.append(Spacer(1, 2*cm))
    story.append(Paragraph("JENIX Enterprise", title_style))
    story.append(Paragraph("Security & Compliance Report", h2_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#00bcd4")))
    story.append(Spacer(1, 0.5*cm))
    story.append(Paragraph(f"<b>Machine:</b> {machine.hostname} ({machine.ip})", body_style))
    story.append(Paragraph(f"<b>OS:</b> {machine.os_name}", body_style))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(Spacer(1, 1*cm))

    # ── Executive Summary ──────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", h2_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#333333")))
    story.append(Spacer(1, 0.3*cm))
    critical_count = sum(1 for a in alerts if a["level"] == "critical")
    warning_count  = sum(1 for a in alerts if a["level"] == "warning")
    risk_score     = min(100, critical_count * 20 + warning_count * 5)
    risk_color     = "#f44336" if risk_score > 60 else "#ff9800" if risk_score > 20 else "#4caf50"
    story.append(Paragraph(
        f'Overall Risk Score: <font color="{risk_color}"><b>{risk_score}/100</b></font>', body_style))
    story.append(Paragraph(f"Critical Alerts: {critical_count}", body_style))
    story.append(Paragraph(f"Warning Alerts:  {warning_count}", body_style))
    summary = (
        f"This report was automatically generated by JENIX Enterprise for {machine.hostname}. "
        f"The system scored {risk_score}/100 on the risk scale. "
        f"{'Immediate action is recommended.' if risk_score > 60 else 'The system appears to be in acceptable health.'}"
    )
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(summary, body_style))
    story.append(Spacer(1, 0.5*cm))

    # ── System Health ──────────────────────────────────────────────────────
    story.append(Paragraph("System Health", h2_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#333333")))
    story.append(Spacer(1, 0.3*cm))
    if metrics:
        avg_cpu  = sum(m["cpu"]  for m in metrics) / len(metrics)
        avg_ram  = sum(m["ram"]  for m in metrics) / len(metrics)
        avg_disk = sum(m["disk"] for m in metrics) / len(metrics)
        health_data = [
            ["Metric", "Average", "Status"],
            ["CPU Usage",  f"{avg_cpu:.1f}%",
             "⚠ High" if avg_cpu > 80  else "✓ OK"],
            ["RAM Usage",  f"{avg_ram:.1f}%",
             "⚠ High" if avg_ram > 85  else "✓ OK"],
            ["Disk Usage", f"{avg_disk:.1f}%",
             "⚠ High" if avg_disk > 90 else "✓ OK"],
        ]
        t = Table(health_data, colWidths=[6*cm, 4*cm, 4*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,0), colors.HexColor("#1e1e2e")),
            ("TEXTCOLOR",    (0,0), (-1,0), colors.HexColor("#00bcd4")),
            ("FONTNAME",     (0,0), (-1,0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),
             [colors.HexColor("#2a2a3e"), colors.HexColor("#1e1e2e")]),
            ("TEXTCOLOR",    (0,1), (-1,-1), colors.white),
            ("GRID",         (0,0), (-1,-1), 0.5, colors.HexColor("#333333")),
            ("ALIGN",        (0,0), (-1,-1), "CENTER"),
            ("PADDING",      (0,0), (-1,-1), 6),
        ]))
        story.append(t)
    story.append(Spacer(1, 0.5*cm))

    # ── Alerts ─────────────────────────────────────────────────────────────
    story.append(Paragraph("Security Alerts", h2_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#333333")))
    story.append(Spacer(1, 0.3*cm))
    if alerts:
        for a in alerts:
            style = crit_style if a["level"] == "critical" else warn_style
            story.append(Paragraph(
                f"[{a['level'].upper()}] {a['type'].upper()} — {a['message']}", style))
    else:
        story.append(Paragraph("No alerts recorded.", body_style))
    story.append(Spacer(1, 0.5*cm))

    # ── Recommendations ────────────────────────────────────────────────────
    story.append(Paragraph("Recommendations", h2_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#333333")))
    story.append(Spacer(1, 0.3*cm))
    recs = []
    if metrics and sum(m["cpu"] for m in metrics)/len(metrics) > 80:
        recs.append("1. CPU usage is consistently high. Review top processes and consider scaling.")
    if metrics and sum(m["ram"] for m in metrics)/len(metrics) > 85:
        recs.append("2. RAM usage is high. Check for memory leaks or increase available RAM.")
    if metrics and sum(m["disk"] for m in metrics)/len(metrics) > 90:
        recs.append("3. Disk usage is critical. Run JENIX Deep Clean or expand storage.")
    if critical_count > 0:
        recs.append("4. Address all critical alerts immediately to reduce security exposure.")
    if not recs:
        recs.append("No immediate recommendations. Continue regular scheduled scans.")
    for r in recs:
        story.append(Paragraph(r, body_style))
    story.append(Spacer(1, 0.5*cm))

    # ── Audit Trail ────────────────────────────────────────────────────────
    story.append(Paragraph("Audit Trail", h2_style))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#333333")))
    story.append(Spacer(1, 0.3*cm))
    if logs:
        log_data = [["Timestamp", "Action", "Detail", "Status"]]
        for l in logs[:15]:
            log_data.append([
                l["timestamp"][:16],
                l["action"],
                textwrap.shorten(l["detail"], 40),
                l["status"]
            ])
        t2 = Table(log_data, colWidths=[4*cm, 3*cm, 7*cm, 2.5*cm])
        t2.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0), colors.HexColor("#1e1e2e")),
            ("TEXTCOLOR",     (0,0), (-1,0), colors.HexColor("#00bcd4")),
            ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS",(0,1), (-1,-1),
             [colors.HexColor("#2a2a3e"), colors.HexColor("#1e1e2e")]),
            ("TEXTCOLOR",     (0,1), (-1,-1), colors.white),
            ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#333333")),
            ("FONTSIZE",      (0,0), (-1,-1), 8),
            ("PADDING",       (0,0), (-1,-1), 5),
        ]))
        story.append(t2)
    else:
        story.append(Paragraph("No audit entries found.", body_style))

    doc.build(story)
    return fname, fpath

# ── Generate report ────────────────────────────────────────────────────────
@router.post("/{machine_id}")
def generate_report(machine_id: int,
                    db: Session = Depends(get_db),
                    current_user: User = Depends(require_operator)):
    m = db.query(Machine).filter(Machine.id == machine_id).first()
    if not m:
        raise HTTPException(status_code=404, detail="Machine not found")
    metrics = db.query(Metric)\
                .filter(Metric.machine_id == machine_id)\
                .order_by(Metric.timestamp.desc())\
                .limit(100).all()
    metrics_list = [{"cpu": x.cpu, "ram": x.ram, "disk": x.disk} for x in metrics]
    logs    = db.query(AuditLog)\
                .filter(AuditLog.machine_id == machine_id)\
                .order_by(AuditLog.timestamp.desc())\
                .limit(20).all()
    logs_list = [{"action": l.action, "detail": l.detail,
                  "status": l.status, "timestamp": l.timestamp.isoformat()} for l in logs]
    alerts  = db.query(Alert)\
                .filter(Alert.machine_id == machine_id)\
                .order_by(Alert.timestamp.desc())\
                .limit(20).all()
    alerts_list = [{"level": a.level, "type": a.type,
                    "message": a.message} for a in alerts]
    fname, fpath = _generate_pdf(m, metrics_list, logs_list, alerts_list)
    size_kb = os.path.getsize(fpath) / 1024
    report  = Report(machine_id=machine_id, filename=fname,
                     filepath=fpath, size_kb=round(size_kb, 1))
    db.add(report); db.commit(); db.refresh(report)
    return {"report_id": report.id, "filename": fname,
            "size_kb": report.size_kb}

# ── List reports ───────────────────────────────────────────────────────────
@router.get("")
def list_reports(db: Session = Depends(get_db),
                 _:  User    = Depends(get_current_user)):
    reports = db.query(Report).order_by(Report.created_at.desc()).all()
    return [{"id": r.id, "machine_id": r.machine_id,
             "filename": r.filename, "size_kb": r.size_kb,
             "created_at": r.created_at.isoformat()} for r in reports]

# ── Download report ────────────────────────────────────────────────────────
@router.get("/{report_id}/download")
def download_report(report_id: int, db: Session = Depends(get_db),
                    _: User = Depends(get_current_user)):
    r = db.query(Report).filter(Report.id == report_id).first()
    if not r or not os.path.exists(r.filepath):
        raise HTTPException(status_code=404, detail="Report not found")
    return FileResponse(r.filepath, media_type="application/pdf",
                        filename=r.filename)

# ── Delete report ──────────────────────────────────────────────────────────
@router.delete("/{report_id}")
def delete_report(report_id: int, db: Session = Depends(get_db),
                  _: User = Depends(require_operator)):
    r = db.query(Report).filter(Report.id == report_id).first()
    if not r:
        raise HTTPException(status_code=404, detail="Report not found")
    if os.path.exists(r.filepath):
        os.remove(r.filepath)
    db.delete(r); db.commit()
    return {"ok": True}
