#!/usr/bin/env python3
"""
JENIX Fleet Key Baking Tool — Stage C

Run this BEFORE building the agent installer with PyInstaller, once per
buyer deployment. It writes the buyer's Ed25519 PUBLIC key (generated by
tools/jenix_keygen.py) into agent/_fleet_key_baked.py, which gets bundled
into the compiled agent binary via JenixAgentCLI.spec's datas list.

The buyer's PRIVATE key is never touched by this script and never should
be anywhere near this machine after the buyer has generated their keypair
— it stays with the buyer, used only by their own signing tooling.

Usage:
  python3 tools/bake_fleet_key.py <public_key_path_or_b64_string>

Examples:
  python3 tools/bake_fleet_key.py test_keys/jenix_fleet_public.key
  python3 tools/bake_fleet_key.py "oW3oJQQI/u4hG86LWA1VmABFK0dUcKFqet69i+4Qq7A="

After running this, build with:
  cd agent
  pyinstaller JenixAgentCLI.spec --clean

IMPORTANT: agent/_fleet_key_baked.py is buyer-specific and gitignored.
Never commit a real buyer's public key into the JENIX source repo — it
belongs only in that buyer's compiled binary.
"""
import sys
import base64
from pathlib import Path

AGENT_DIR = Path(__file__).resolve().parent.parent / "agent"
BAKED_FILE = AGENT_DIR / "_fleet_key_baked.py"


def resolve_key(arg: str) -> str:
    """Accept either a path to a key file, or a raw base64 string."""
    p = Path(arg)
    if p.exists():
        raw = p.read_text().strip()
    else:
        raw = arg.strip()
    return raw


def validate_b64_ed25519_pubkey(b64_str: str) -> bool:
    try:
        decoded = base64.b64decode(b64_str, validate=True)
    except Exception:
        return False
    # Ed25519 public keys are exactly 32 raw bytes
    return len(decoded) == 32


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 bake_fleet_key.py <public_key_path_or_b64_string>")
        print("       (leave empty string \"\" to disable fleet signing on this build)")
        sys.exit(1)

    arg = sys.argv[1]

    if arg == "":
        key_b64 = ""
        print("[bake_fleet_key] Baking EMPTY key — fleet signing will be DISABLED on this build.")
    else:
        key_b64 = resolve_key(arg)
        if not validate_b64_ed25519_pubkey(key_b64):
            print(f"[bake_fleet_key] ERROR: '{key_b64[:20]}...' is not a valid 32-byte "
                  f"base64-encoded Ed25519 public key. Refusing to bake a bad key.")
            sys.exit(1)
        print(f"[bake_fleet_key] Validated Ed25519 public key ({len(base64.b64decode(key_b64))} bytes).")

    if not AGENT_DIR.exists():
        print(f"[bake_fleet_key] ERROR: agent dir not found at {AGENT_DIR}")
        sys.exit(1)

    content = (
        f'FLEET_PUBLIC_KEY_B64 = "{key_b64}"  '
        f'# baked by tools/bake_fleet_key.py — buyer-specific, do not commit\n'
    )
    BAKED_FILE.write_text(content)

    print(f"[bake_fleet_key] Wrote {BAKED_FILE}")
    print(f"[bake_fleet_key] Content: {content.strip()}")
    print()
    print("[bake_fleet_key] Next step: cd agent && pyinstaller JenixAgentCLI.spec --clean")


if __name__ == "__main__":
    main()
